{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">缓存管理</div>

<div class="massaction">
<a href="{$r}caches/list">系统缓存</a>  |  
<a href="{$r}caches/list/ctype/smarty">模板缓存</a>  |  
<a href="{$r}caches/clear">更新系统缓存</a>  |  
<a href="{$r}caches/clear/ctype/smarty">清空模板缓存</a>
</div>
	
<table class="bd_c_1" cellpadding="0" cellspacing="0">
	<tr class="headings">
		<td>文件名</td>
		<td>创建时间</td>
		<td>文件大小</td>
	</tr>
{foreach from=$caches item=item}
	<tr>
		<td bgcolor="#F6F6F6">{$item.fname}</td>
		<td bgcolor="#F6F6F6">{$item.ftime}</td>
		<td bgcolor="#F6F6F6">{$item.fsize}</td>
	</tr>
{/foreach}
</table>
</div>
{include file="page_footer.lbi"}