<div class="location">修改功能</div>

<form action="<?php echo $this->r; ?>function/edit" method="post" name="addform">
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr>
			<td>
			<label>功能修改:</label>
			<input type="text" name="name" value="<?php echo $this->RsInfo[0]['name'];?>" size=64/>
			<input type="hidden" name="id" value="<?php echo $this->RsInfo[0]['id'];?>"/>
			<input type="submit" name="rsubmit" value="修改 " class="buttons_a"/>
			</td>
		</tr>
		<tr><label><?php echo $this->msgFunction;?></label></tr>
	</table>
</form>