<?php

/**
 * Default home page view
 *  
 * @author
 * @version
 */

$this->headTitle('登录WOC网站运营中心');
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo $this->headTitle();
echo $this->headScript()->appendFile($this->r.'skin/js/yahoo-dom-event.js')
	    		->appendFile($this->r.'skin/js/yahoo.js')
	    		->appendFile($this->r.'skin/js/event.js')
	    		->appendFile($this->r.'skin/js/connection.js')
	    		->appendFile($this->r.'skin/js/json.js')
	    		->appendFile($this->r.'skin/js/login.js')
	    		->appendFile($this->r.'skin/js/jquery.js');
echo $this->headLink()->appendStylesheet($this->r."skin/style/login.css");
?>
</head>
<body onload="document.getElementById('name').focus();">
<form name="login" action="<?php echo $this->r; ?>auth/login" method="post">
	<div id="conter">
	<div id="left"></div>
	<div id="right">
	<div id="right_logo">登录WOC网站运营中心</div>
	<div id="right_search">
	<div id="right_search1">用户名<br><input type="text" id="name" name="name" value="<?php echo $this->Name;?>" size="25"/></div>
	<div id="right_search2">密码<br><input type="password" name="password" id="pass" value="" size="25"/></div>
	<div class="clear"></div>
	<div style="font-size:12px; color:#ff0000; margin-top:10px;"><?php echo $this->msgName;?><?php echo $this->msgPass;?><?php echo $this->msgError;?></div>
	</div>
	<div id="right_anniu"><input type="image" name="slogin" src="<?php echo $this->r; ?>skin/images/an.gif"/></div>
	<div id="right_foot">WOC ™ is a trademark of WOC. . Copyright © 2007-2011 WOC Software Inc(YJZZJ.COM).</div>
	</div>
	</div>
</form>
</body>
</html>
