{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">修改主机</div>

<form action="{$r}host/edit" method="post" name="addform">
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr><label>{$msgSite}</label></tr>
		<tr>
			<td><label>主机IP:</label><input type="text" name="ip" value="{$rsInfo.ip}" size=30/></td>
		</tr>
		<tr>
			<td><label>管理入口:</label><input type="text" name="admin" value="{$rsInfo.admin}" size=30/></td>
		</tr>
		<tr>
			<td><label>管理账号:</label><input type="text" name="username" value="{$rsInfo.username}" size=30/></td>
		</tr>
		<tr>
			<td><label>管理账号:</label><input type="text" name="password" value="{$rsInfo.password}" size=30/></td>
		</tr>
		<tr>
			<td><label>供应商户:</label><input type="text" name="provider" value="{$rsInfo.provider}" size=30/></td>
		</tr>
		<tr>
			<td>
			<label>主机状态:</label>
			<input type="radio" name="status" id="status0" value="0"{if 0 == $rsInfo.status} checked{/if}/><label for="status0">使用中</label>
			<input type="radio" name="status" id="status1" value="1"{if 1 == $rsInfo.status} checked{/if}/><label for="status1">已出错</label>
			<input type="radio" name="status" id="status1" value="2"{if 2 == $rsInfo.status} checked{/if}/><label for="status1">维护中</label>
			<input type="radio" name="status" id="status1" value="3"{if 3 == $rsInfo.status} checked{/if}/><label for="status1">已停用</label>
			</td>
		</tr>
		<input type="hidden" name="id" value="{$rsInfo.id}"/>
		<tr>
			<td><input type="submit" name="rsubmit" value="修改 " class="buttons_a"/></td>
		</tr>
	</table>
</form>
</div>
{include file="page_footer.lbi"}