{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">修改功能</div>

<form action="{$r}function/edit" method="post" name="addform">
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr>
			<td>
			<label>功能修改:</label>
			<input type="text" name="name" value="{$RsInfo.0.name}" size=64/>
			<input type="hidden" name="id" value="{$RsInfo.0.id}"/>
			<input type="submit" name="rsubmit" value="修改 " class="buttons_a"/>
			</td>
		</tr>
		<tr><label>{$msgFunction}</label></tr>
	</table>
</form>
</div>
{include file="page_footer.lbi"}