{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">修改分类</div>

<form action="{$r}type/edit" method="post" name="addform">
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr>
			<td><label>分类修改:</label><input type="text" name="name" value="{$rsInfo.name}" size=64/><input type="submit" name="rsubmit" value="修改" class="buttons_a"/></td>
		</tr>
		<input type="hidden" name="id" value="{$rsInfo.tid}"/>
		<tr><label>{$msgPT}</label></tr>
	</table>
</form>
</div>
{include file="page_footer.lbi"}