{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">网站分类</div>

<div class="massaction"><a href="{$r}type/add">添加</a></div>
	
<table class="bd_c_1" cellpadding="0" cellspacing="0">
	<tr class="headings">
		<td>编号</td>
		<td>名称</td>
		<td>操作</td>
	</tr>
{foreach from=$paginator key=i item=item}
{if $i%2 == 0}
	<tr bgcolor="#F6F6F6">
		<td>{$item->tid }</td>
		<td>{$item->name }</td>
		<td><a href="{$r}type/edit/id/{$item->tid }">修改</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{$r}type/delete/id/{$item->tid }">删除</a></td>
	</tr>
{else}
	<tr>
		<td>{$item->tid }</td>
		<td>{$item->name }</td>
		<td><a href="{$r}type/edit/id/{$item->tid }">修改</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{$r}type/delete/id/{$item->tid }">删除</a></td>
	</tr>
{/if}
{/foreach}
	<tr>
		<td colspan="3" align="right">{include file="my_pagination_control.lbi"}</td>
	</tr>
</table>
</div>
{include file="page_footer.lbi"}