{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">用户添加</div>
<form action="{$r}user/add" method="post" name="addform">
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr>
			<td><label>用户名称:</label></td><td><input type="text" name="name" class="ipt_m" value="{$name}" size="18"/></td><td>{$msgName}</td>
		</tr>
		<tr>
			<td><label>密码:</label></td><td><input type="password" name="pass" class="ipt_m" value="" size="18"/></td><td>{$msgPass}</td>
		</tr>
		<tr>
			<td><label>重复密码:</label></td><td><input type="password" name="repass" class="ipt_m" value="" size="18"/></td><td>{$msgRepass}</td>
		</tr>
		<tr>
			<td><label>电子邮箱:</label></td><td><input type="text" name="email"  class="ipt_m" value="{$email}" size="18"/></td><td>{$msgEmail}</td>
		</tr>
		<tr>
			<td><label>联系电话:</label></td>
			<td>
				<input type="text" name="tel" class="ipt_m" value="{$tel}" size="18"/></td>
			
			<td>{$msgTelephone}</td>
		</tr>
		<tr>
			<td><label>状态:</label></td>
			<td>
				<input type="radio" name="status" id="status0" value="0"/><label for="status0">禁用</label><input type="radio" name="status" id="status1" value="1" checked/><label for="status1">开启</label>
			</td><td></td>
		</tr>
		<tr>
			<td><label>所属角色:</label></td>
			<td>
				<select name="role">

					{foreach from=$rs item=item}
						<option value="{$item.name}|{$item.rid}">{$item.name}</option>
					{/foreach}
				</select>
			</td>
			<td></td>
		</tr>
		<tr>
			<td><label>所属产品:</label></td>
			<td>
				<select name="product">
					<option value="All Product|0">全部</option>
					{foreach from=$pt item=item}
						<option value="{$item.name}|{$item.ptid}">{$item.name}</option>
					{/foreach}
				</select>
			</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="3"><input type="submit" name="rsubmit" value="添加" class="buttons_a"/></td>
		</tr>
	</table>
</form>
</div>
{include file="page_footer.lbi"}