{include file="page_header.lbi"}
<div id="col1">{include file="page_sidebar.lbi"}</div>
<div id="col2">
<div class="location">用户管理</div>  

<div class="massaction"><a href="{$r}user/add">添加</a></div>
	
<table class="bd_c_1" cellpadding="0" cellspacing="0">
		<tr class="headings">
		<td>编号</td>
		<td>真实姓名</td>
		<td>所属分组</td>
		<td>电子邮箱</td>
		<td>联系电话</td>
		<td>状态</td>
		<td>最后登陆时间</td>
		<td>最后登陆ip</td>
		<td>操作</td>	
	</tr>
{foreach from=$paginator key=i item=item}
	{if $i%2 == 0}
		<tr bgcolor="#F6F6F6">
			<td>{$item.uid}</td>
			<td>{$item.name}</td>
			<td>{$item.rname}</td>
			<td>{$item.email}</td>
			<td>{$item.telphone}</td>
			<td>{if $item.status}启用{else}禁止{/if}</td>
			<td>{$item.access|date_format:"%Y-%m-%d %H:%M:%S"}</td>
			<td>{$item.ip}</td>
			<td><a href="{$r}user/edit/id/{$item.uid}">修改</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{$r}user/delete/id/{$item.uid}">删除</a></td>
		</tr>
	{else}
		<tr>
			<td>{$item.uid}</td>
			<td>{$item.name}</td>
			<td>{$item.rname}</td>
			<td>{$item.email}</td>
			<td>{$item.telphone}</td>
			<td>{if $item.status}启用{else}禁止{/if}</td>
			<td>{$item.access|date_format:"%Y-%m-%d %H:%M:%S"}</td>
			<td>{$item.ip}</td>
			<td><a href="{$r}user/edit/id/{$item.uid}">修改</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{$r}user/delete/id/{$item.uid}">删除</a></td>
		</tr>
	{/if}
{/foreach}
	<tr>
		<td colspan="9" align="right">{include file="my_pagination_control.lbi"}</td>
	</tr>
</table>
</div>
{include file="page_footer.lbi"}